export type PackCategory = 'baseline' | 'size' | 'vertical';

export interface PackSetting {
  key: string;
  rawValue: string; // JSON string — parse before POST
  comment?: string;
}

export interface SettingsPack {
  id: string;
  name: string;
  category: PackCategory;
  description: string;
  settings: PackSetting[];
}

const PACKS: SettingsPack[] = [
  // ─── Global Baseline ───────────────────────────────────────────────────────
  {
    id: 'global',
    name: 'Global Baseline',
    category: 'baseline',
    description: 'Universal defaults every Kenyan tenant needs: currency, VAT, eTIMS, M-Pesa, receipts, POS, DPA. Install this first before any other pack.',
    settings: [
      { key: 'currency', rawValue: '"KES"', comment: 'Kenyan Shilling' },
      { key: 'currency.symbol', rawValue: '"KSh"' },
      { key: 'currency.code_iso', rawValue: '"KES"' },
      { key: 'currency.decimal_places', rawValue: '2' },
      { key: 'currency.thousands_separator', rawValue: '","' },
      { key: 'tax_rate', rawValue: '0.16', comment: 'Kenya VAT 16%' },
      { key: 'tax.zero_rated_enabled', rawValue: 'true' },
      { key: 'tax.exempt_enabled', rawValue: 'true' },
      { key: 'fiscal_year_start', rawValue: '"01-01"' },
      { key: 'rounding_mode', rawValue: '"nearest"' },
      { key: 'ui.theme', rawValue: '"light"' },
      { key: 'ui.language', rawValue: '"en"' },
      { key: 'ui.timezone', rawValue: '"Africa/Nairobi"' },
      { key: 'ui.date_format', rawValue: '"DD/MM/YYYY"' },
      { key: 'ui.time_format', rawValue: '"24h"' },
      { key: 'business.registered_name', rawValue: '""', comment: 'Fill in: legal business name' },
      { key: 'business.kra_pin', rawValue: '""', comment: 'Fill in: KRA PIN for eTIMS' },
      { key: 'business.physical_address', rawValue: '""' },
      { key: 'business.phone', rawValue: '""' },
      { key: 'business.email', rawValue: '""' },
      { key: 'etims.enabled', rawValue: 'true' },
      { key: 'etims.offline_queue_enabled', rawValue: 'true' },
      { key: 'etims.auto_submit', rawValue: 'true' },
      { key: 'etims.retry_max_attempts', rawValue: '5' },
      { key: 'mpesa.enabled', rawValue: 'true' },
      { key: 'mpesa.stk_push_enabled', rawValue: 'true' },
      { key: 'mpesa.manual_entry_enabled', rawValue: 'true' },
      { key: 'receipt.header', rawValue: '"{{business.registered_name}}"' },
      { key: 'receipt.footer', rawValue: '"Asante kwa ununuzi wenu / Thank you for shopping with us"' },
      { key: 'receipt.show_kra_pin', rawValue: 'true' },
      { key: 'receipt.show_qr_code', rawValue: 'true' },
      { key: 'receipt.print_after_sale', rawValue: 'true' },
      { key: 'receipt.email_after_sale', rawValue: 'false' },
      { key: 'receipt.sms_after_sale', rawValue: 'false' },
      { key: 'pos.default_payment_method', rawValue: '"cash"' },
      { key: 'pos.barcode_scanner_enabled', rawValue: 'true' },
      { key: 'pos.allow_negative_stock', rawValue: 'false' },
      { key: 'pos.require_customer_for_sales_over', rawValue: 'null' },
      { key: 'pos.cash_drawer_auto_open', rawValue: 'true' },
      { key: 'pos.receipt_copy_count', rawValue: '1' },
      { key: 'inventory.default_reorder_threshold', rawValue: '10' },
      { key: 'inventory.low_stock_alerts_enabled', rawValue: 'true' },
      { key: 'notifications.email.enabled', rawValue: 'true' },
      { key: 'notifications.sms.enabled', rawValue: 'false', comment: 'SMS costs money — opt-in' },
      { key: 'notifications.low_stock.recipients_role', rawValue: '["manager","stock_manager"]' },
      { key: 'notifications.large_sale_threshold', rawValue: '100000', comment: 'KES 100k alert' },
      { key: 'backup.daily_enabled', rawValue: 'true' },
      { key: 'backup.retention_days', rawValue: '90' },
      { key: 'audit.enabled', rawValue: 'true' },
      { key: 'audit.retention_days', rawValue: '730', comment: '2 years — Kenya DPA' },
      { key: 'dpa.customer_consent_required', rawValue: 'true', comment: 'Kenya Data Protection Act 2019' },
      { key: 'dpa.breach_notification_email', rawValue: '""', comment: 'Fill in: DPO email' },
    ],
  },

  // ─── 1. Retail — Small / Single-location ───────────────────────────────────
  {
    id: 'retail_small',
    name: 'Retail — Small / Single-location',
    category: 'size',
    description: 'Shop, boutique, mini-mart. 1–3 locations, KES 5–50M annual revenue. Sensible POS defaults with manual reorder.',
    settings: [
      { key: 'pos.cash_drawer_auto_open', rawValue: 'true' },
      { key: 'pos.receipt_copy_count', rawValue: '1' },
      { key: 'pos.quick_cash_buttons', rawValue: '[50,100,200,500,1000,2000]' },
      { key: 'pos.held_sale_expiry_hours', rawValue: '24' },
      { key: 'pos.scan_only_mode_enabled', rawValue: 'false' },
      { key: 'pos.require_customer_for_sales_over', rawValue: 'null' },
      { key: 'inventory.default_reorder_threshold', rawValue: '5' },
      { key: 'inventory.auto_reorder_enabled', rawValue: 'false' },
      { key: 'inventory.overstock_alert_multiple', rawValue: '4' },
      { key: 'pricing.volume_discount_enabled', rawValue: 'true' },
      { key: 'pricing.weekend_premium_enabled', rawValue: 'false' },
      { key: 'customers.loyalty_enabled', rawValue: 'false' },
      { key: 'customers.require_phone_at_pos', rawValue: 'false' },
      { key: 'reports.daily_closing_time', rawValue: '"20:00"' },
      { key: 'reports.daily_closing_recipients_role', rawValue: '["manager"]' },
      { key: 'receipt.show_item_discount', rawValue: 'true' },
      { key: 'receipt.show_you_saved', rawValue: 'true' },
    ],
  },

  // ─── 2. Retail — Multi-location Chain ──────────────────────────────────────
  {
    id: 'retail_chain',
    name: 'Retail — Multi-location Chain',
    category: 'size',
    description: '3–20 locations, centrally managed, KES 50M–2B revenue. Central pricing, inter-branch transfers, consolidated reporting.',
    settings: [
      { key: 'multi_location.enabled', rawValue: 'true' },
      { key: 'multi_location.central_reporting_enabled', rawValue: 'true' },
      { key: 'multi_location.transfer_approval_required', rawValue: 'true' },
      { key: 'multi_location.transfer_approval_threshold_value', rawValue: '50000' },
      { key: 'multi_location.location_isolation_mode', rawValue: '"soft"' },
      { key: 'inventory.sync_across_locations', rawValue: 'true' },
      { key: 'inventory.show_other_location_stock_at_pos', rawValue: 'true' },
      { key: 'inventory.cross_location_transfer_auto_suggest', rawValue: 'true' },
      { key: 'pricing.per_location_pricing_enabled', rawValue: 'true' },
      { key: 'pricing.central_pricing_enforced', rawValue: 'true' },
      { key: 'reports.consolidated_daily_summary', rawValue: 'true' },
      { key: 'reports.per_location_performance', rawValue: 'true' },
      { key: 'approvals.void_cross_location_denied', rawValue: 'true' },
      { key: 'approvals.refund_requires_original_location', rawValue: 'false' },
      { key: 'staff.home_location_required', rawValue: 'true' },
      { key: 'staff.cross_location_transfer_approval', rawValue: 'true' },
    ],
  },

  // ─── 3. Pharmacy ───────────────────────────────────────────────────────────
  {
    id: 'pharmacy',
    name: 'Pharmacy (Kenya)',
    category: 'vertical',
    description: 'Licensed pharmacies under PPB regulation. Batch tracking, cold chain, POM controls, insurance claims, refill reminders.',
    settings: [
      { key: 'pharmacy.enabled', rawValue: 'true' },
      { key: 'pharmacy.ppb_license_number', rawValue: '""', comment: 'Fill in: PPB license' },
      { key: 'pharmacy.pharmacist_in_charge', rawValue: '""', comment: 'Fill in: user ID' },
      { key: 'pharmacy.batch_tracking_mandatory', rawValue: 'true' },
      { key: 'pharmacy.expiry_warning_days', rawValue: '90' },
      { key: 'pharmacy.near_expiry_critical_days', rawValue: '30' },
      { key: 'pharmacy.block_expired_sale', rawValue: 'true' },
      { key: 'pharmacy.discount_near_expiry_enabled', rawValue: 'true' },
      { key: 'pharmacy.discount_near_expiry_percent', rawValue: '30' },
      { key: 'pharmacy.cold_chain_enabled', rawValue: 'true' },
      { key: 'pharmacy.cold_chain_breach_alert', rawValue: 'true' },
      { key: 'pharmacy.pom_sale_requires_pharmacist', rawValue: 'true' },
      { key: 'pharmacy.controlled_substance_requires_two_person', rawValue: 'true' },
      { key: 'pharmacy.prescription_photo_required', rawValue: 'true' },
      { key: 'pharmacy.insurance_claim.enabled', rawValue: 'true' },
      { key: 'pharmacy.insurance_claim.providers', rawValue: '["NHIF","SHA","AAR","Jubilee","CIC","Britam","Madison","APA"]' },
      { key: 'pharmacy.insurance_claim.auto_generate', rawValue: 'true' },
      { key: 'pharmacy.refill_reminder.enabled', rawValue: 'true' },
      { key: 'pharmacy.refill_reminder.days_before_run_out', rawValue: '7' },
      { key: 'pharmacy.refill_reminder.channel', rawValue: '"sms"' },
      { key: 'notifications.sms.enabled', rawValue: 'true', comment: 'Required for refill reminders' },
    ],
  },

  // ─── 4. Hardware Store ─────────────────────────────────────────────────────
  {
    id: 'hardware',
    name: 'Hardware Store',
    category: 'vertical',
    description: 'Building supplies, tools, electrical, plumbing. Contractor discounts, credit accounts, quotes, volumetric delivery.',
    settings: [
      { key: 'hardware.enabled', rawValue: 'true' },
      { key: 'pos.barcode_scanner_enabled', rawValue: 'true' },
      { key: 'pos.quick_cash_buttons', rawValue: '[100,500,1000,2000,5000,10000]' },
      { key: 'customers.contractor_segment_enabled', rawValue: 'true' },
      { key: 'pricing.contractor_discount_percent', rawValue: '10' },
      { key: 'pricing.contractor_min_purchase_for_discount', rawValue: '5000' },
      { key: 'pricing.developer_discount_percent', rawValue: '15' },
      { key: 'credit.enabled', rawValue: 'true' },
      { key: 'credit.default_limit', rawValue: '50000' },
      { key: 'credit.default_terms_days', rawValue: '30' },
      { key: 'credit.blocked_over_limit', rawValue: 'true' },
      { key: 'credit.manager_override_enabled', rawValue: 'true' },
      { key: 'quotes.enabled', rawValue: 'true' },
      { key: 'quotes.default_validity_days', rawValue: '14' },
      { key: 'quotes.auto_convert_to_sale_on_accept', rawValue: 'false' },
      { key: 'delivery.enabled', rawValue: 'true' },
      { key: 'delivery.free_threshold', rawValue: '50000' },
      { key: 'delivery.default_fee', rawValue: '1500' },
      { key: 'delivery.volumetric_weight_enabled', rawValue: 'true' },
      { key: 'inventory.auto_reorder_enabled', rawValue: 'true' },
      { key: 'inventory.default_reorder_threshold', rawValue: '20' },
    ],
  },

  // ─── 5. Restaurant / Café ──────────────────────────────────────────────────
  {
    id: 'restaurant',
    name: 'Restaurant / Café',
    category: 'vertical',
    description: 'Food service with table management, kitchen display, recipe costing, happy hour, delivery platforms, and liquor license support.',
    settings: [
      { key: 'restaurant.enabled', rawValue: 'true' },
      { key: 'restaurant.table_management.enabled', rawValue: 'true' },
      { key: 'restaurant.table_management.default_tables', rawValue: '20' },
      { key: 'restaurant.order_types', rawValue: '["dine_in","takeaway","delivery"]' },
      { key: 'restaurant.kitchen_display_enabled', rawValue: 'true' },
      { key: 'restaurant.kitchen_stations', rawValue: '["grill","fryer","cold_kitchen","bar","barista"]' },
      { key: 'restaurant.recipe_costing.enabled', rawValue: 'true' },
      { key: 'restaurant.recipe_costing.auto_deduct_ingredients', rawValue: 'true' },
      { key: 'restaurant.recipe_costing.waste_percent_default', rawValue: '5' },
      { key: 'restaurant.happy_hour.enabled', rawValue: 'true' },
      { key: 'restaurant.happy_hour.start', rawValue: '"17:00"' },
      { key: 'restaurant.happy_hour.end', rawValue: '"19:00"' },
      { key: 'restaurant.happy_hour.discount_percent', rawValue: '20' },
      { key: 'restaurant.happy_hour.applies_to_category', rawValue: '["drinks","appetizers"]' },
      { key: 'restaurant.tip_suggestion_percents', rawValue: '[10,12,15]' },
      { key: 'restaurant.service_charge_enabled', rawValue: 'false' },
      { key: 'restaurant.service_charge_percent', rawValue: '10' },
      { key: 'restaurant.delivery.enabled', rawValue: 'true' },
      { key: 'restaurant.delivery.providers', rawValue: '["Uber Eats","Glovo","Jumia Food","Bolt Food","own"]' },
      { key: 'restaurant.delivery.commission_applies', rawValue: 'true' },
      { key: 'restaurant.liquor_license.enabled', rawValue: 'false' },
      { key: 'restaurant.liquor_license.number', rawValue: '""' },
      { key: 'restaurant.liquor_license.hours_start', rawValue: '"11:00"' },
      { key: 'restaurant.liquor_license.hours_end', rawValue: '"22:30"' },
      { key: 'pos.default_payment_method', rawValue: '"mpesa"' },
      { key: 'pos.split_bill_enabled', rawValue: 'true' },
      { key: 'pos.bill_print_before_payment', rawValue: 'true' },
    ],
  },

  // ─── 6. Agricultural Inputs ────────────────────────────────────────────────
  {
    id: 'agri',
    name: 'Agricultural Inputs',
    category: 'vertical',
    description: 'Agro-dealers serving farmers. PCPB compliance, seasonal tracking, toxicity warnings, cooperative discounts, farm delivery.',
    settings: [
      { key: 'agri.enabled', rawValue: 'true' },
      { key: 'agri.pcpb_license_number', rawValue: '""', comment: 'Fill in: PCPB license' },
      { key: 'agri.season.current', rawValue: '"long_rains"' },
      { key: 'agri.season.long_rains_start', rawValue: '"03-15"' },
      { key: 'agri.season.long_rains_end', rawValue: '"06-15"' },
      { key: 'agri.season.short_rains_start', rawValue: '"10-01"' },
      { key: 'agri.season.short_rains_end', rawValue: '"12-15"' },
      { key: 'agri.toxicity_warning.enabled', rawValue: 'true' },
      { key: 'agri.toxicity_warning.class_i_requires_approval', rawValue: 'true' },
      { key: 'agri.phi_warning.enabled', rawValue: 'true' },
      { key: 'agri.batch_tracking_mandatory', rawValue: 'true' },
      { key: 'agri.expiry_warning_months', rawValue: '6' },
      { key: 'agri.cooperative_discount_enabled', rawValue: 'true' },
      { key: 'agri.cooperative_discount_percent', rawValue: '8' },
      { key: 'credit.enabled', rawValue: 'true' },
      { key: 'credit.default_terms_days', rawValue: '90', comment: 'Post-harvest payment' },
      { key: 'credit.harvest_aligned_due_dates', rawValue: 'true' },
      { key: 'pricing.bulk_breaks_enabled', rawValue: 'true' },
      { key: 'delivery.farm_delivery_enabled', rawValue: 'true' },
      { key: 'delivery.ward_based_routing', rawValue: 'true' },
      { key: 'education.extension_advice_enabled', rawValue: 'true' },
      { key: 'education.seasonal_tips_enabled', rawValue: 'true' },
    ],
  },

  // ─── 7. Electronics Retail ─────────────────────────────────────────────────
  {
    id: 'electronics',
    name: 'Electronics Retail',
    category: 'vertical',
    description: 'Phones, laptops, TVs, appliances. IMEI/serial tracking, warranty management, returns, demo units, accessory upsell.',
    settings: [
      { key: 'electronics.enabled', rawValue: 'true' },
      { key: 'electronics.imei_tracking_required', rawValue: 'true' },
      { key: 'electronics.serial_tracking_required', rawValue: 'true' },
      { key: 'electronics.warranty.default_months', rawValue: '12' },
      { key: 'electronics.warranty.registration_email', rawValue: 'true' },
      { key: 'electronics.warranty.claim_approval_role', rawValue: '"service_manager"' },
      { key: 'electronics.return_window_days', rawValue: '14' },
      { key: 'electronics.return_requires_original_packaging', rawValue: 'true' },
      { key: 'electronics.return_restocking_fee_percent', rawValue: '10' },
      { key: 'electronics.demo_units.tracked', rawValue: 'true' },
      { key: 'electronics.demo_units.max_demo_days', rawValue: '14' },
      { key: 'electronics.accessories.auto_suggest', rawValue: 'true' },
      { key: 'electronics.trade_in.enabled', rawValue: 'false' },
      { key: 'pricing.open_box_discount_percent', rawValue: '10' },
      { key: 'pricing.refurbished_disclosure_required', rawValue: 'true' },
      { key: 'installation.enabled', rawValue: 'true' },
      { key: 'installation.default_fee', rawValue: '2000' },
      { key: 'installation.free_threshold', rawValue: '100000' },
    ],
  },

  // ─── 8. Wholesale Distribution ─────────────────────────────────────────────
  {
    id: 'wholesale',
    name: 'Wholesale Distribution',
    category: 'vertical',
    description: 'FMCG distributors and B2B bulk sellers. MOQ pricing, credit aging, route optimization, sales rep commissions.',
    settings: [
      { key: 'wholesale.enabled', rawValue: 'true' },
      { key: 'wholesale.min_order_value', rawValue: '5000' },
      { key: 'wholesale.default_order_unit', rawValue: '"case"' },
      { key: 'credit.enabled', rawValue: 'true' },
      { key: 'credit.default_terms_days', rawValue: '30' },
      { key: 'credit.aging_reminders.enabled', rawValue: 'true' },
      { key: 'credit.aging_reminders.days_before_due', rawValue: '[7,3,1]' },
      { key: 'credit.aging_reminders.days_after_due', rawValue: '[1,7,14,30]' },
      { key: 'credit.overdue_interest_percent_per_month', rawValue: '2' },
      { key: 'pricing.moq_breaks_enabled', rawValue: 'true' },
      { key: 'pricing.customer_specific_pricing_enabled', rawValue: 'true' },
      { key: 'pricing.contract_pricing_enabled', rawValue: 'true' },
      { key: 'route.optimization_enabled', rawValue: 'true' },
      { key: 'route.max_stops_per_route', rawValue: '25' },
      { key: 'route.planning_frequency', rawValue: '"weekly"' },
      { key: 'delivery.truck_loading_required', rawValue: 'true' },
      { key: 'sales_reps.enabled', rawValue: 'true' },
      { key: 'sales_reps.commission_enabled', rawValue: 'true' },
      { key: 'sales_reps.commission_default_percent', rawValue: '2' },
      { key: 'sales_reps.target_tracking_enabled', rawValue: 'true' },
      { key: 'returns.goods_return_window_days', rawValue: '30' },
      { key: 'returns.requires_approval', rawValue: 'true' },
      { key: 'returns.restocking_fee_percent', rawValue: '0' },
      { key: 'reporting.sales_by_rep', rawValue: 'true' },
      { key: 'reporting.sales_by_route', rawValue: 'true' },
      { key: 'reporting.sales_by_customer', rawValue: 'true' },
      { key: 'reporting.margin_by_sku', rawValue: 'true' },
    ],
  },

  // ─── 9. Auto Parts ─────────────────────────────────────────────────────────
  {
    id: 'auto_parts',
    name: 'Auto Parts',
    category: 'vertical',
    description: 'Automotive parts dealers. Compatibility warnings, supersession, core charges, workshop/fleet accounts and discounts.',
    settings: [
      { key: 'auto_parts.enabled', rawValue: 'true' },
      { key: 'auto_parts.compatibility_check.enabled', rawValue: 'true' },
      { key: 'auto_parts.compatibility_check.warn_on_mismatch', rawValue: 'true' },
      { key: 'auto_parts.compatibility_check.block_on_mismatch', rawValue: 'false' },
      { key: 'auto_parts.alternatives.show_at_pos', rawValue: 'true' },
      { key: 'auto_parts.supersession.auto_suggest', rawValue: 'true' },
      { key: 'auto_parts.core_charge.enabled', rawValue: 'true' },
      { key: 'auto_parts.core_charge.refund_window_days', rawValue: '30' },
      { key: 'auto_parts.vin_lookup.enabled', rawValue: 'false' },
      { key: 'customers.workshop_accounts.enabled', rawValue: 'true' },
      { key: 'pricing.workshop_discount_percent', rawValue: '15' },
      { key: 'pricing.fleet_discount_percent', rawValue: '20' },
      { key: 'credit.workshop_default_limit', rawValue: '100000' },
      { key: 'credit.workshop_default_terms_days', rawValue: '30' },
      { key: 'credit.fleet_default_limit', rawValue: '500000' },
      { key: 'credit.fleet_default_terms_days', rawValue: '45' },
      { key: 'warranty.default_months', rawValue: '3' },
      { key: 'warranty.genuine_oem_months', rawValue: '12' },
      { key: 'inventory.fast_moving_reorder_threshold', rawValue: '15' },
      { key: 'inventory.slow_moving_review_days', rawValue: '180' },
    ],
  },

  // ─── 10. Beauty / Cosmetics ────────────────────────────────────────────────
  {
    id: 'beauty',
    name: 'Beauty / Cosmetics',
    category: 'vertical',
    description: 'Beauty retailers and salon retail. Batch/PAO tracking, skin consultation, tiered loyalty, samples, gift wrap.',
    settings: [
      { key: 'beauty.enabled', rawValue: 'true' },
      { key: 'beauty.batch_tracking_mandatory', rawValue: 'true' },
      { key: 'beauty.expiry_warning_months', rawValue: '3' },
      { key: 'beauty.pao_warning_enabled', rawValue: 'true' },
      { key: 'beauty.consultation.enabled', rawValue: 'true' },
      { key: 'beauty.consultation.skin_type_required', rawValue: 'true' },
      { key: 'beauty.loyalty.enabled', rawValue: 'true' },
      { key: 'beauty.loyalty.tiers', rawValue: '["standard","silver","gold","platinum"]' },
      { key: 'beauty.loyalty.spend_silver', rawValue: '10000' },
      { key: 'beauty.loyalty.spend_gold', rawValue: '50000' },
      { key: 'beauty.loyalty.spend_platinum', rawValue: '250000' },
      { key: 'beauty.loyalty.points_per_kes', rawValue: '1' },
      { key: 'beauty.loyalty.points_redemption_value', rawValue: '0.02' },
      { key: 'beauty.samples.enabled', rawValue: 'true' },
      { key: 'beauty.samples.no_charge', rawValue: 'true' },
      { key: 'beauty.gift_wrap.enabled', rawValue: 'true' },
      { key: 'beauty.gift_wrap.fee', rawValue: '200' },
      { key: 'beauty.returns_on_opened_products', rawValue: 'false' },
      { key: 'beauty.return_window_days', rawValue: '30' },
      { key: 'pricing.premium_brand_markup_percent', rawValue: 'null' },
      { key: 'pricing.testers_discount_percent', rawValue: '50' },
    ],
  },
];

export function useSettingsPacks() {
  const packs = computed(() => PACKS);

  const byCategory = computed(() => ({
    baseline: PACKS.filter((p) => p.category === 'baseline'),
    size: PACKS.filter((p) => p.category === 'size'),
    vertical: PACKS.filter((p) => p.category === 'vertical'),
  }));

  return { packs, byCategory };
}
